# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170920_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='imagem',
        ),
        migrations.AddField(
            model_name='depoimento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destaque',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Imovel'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
