# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170921_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destaque',
            old_name='titilo',
            new_name='titulo',
        ),
    ]
